name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg

          # GitHub username
          user: vibhuti019

          # Base sections
          base: header, activity, community, repositories, metadata

          # Theme
          config_timezone: Asia/Kolkata
          config_display: large
          template: classic
          theme: tokyonight

          # Plugins
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes

          plugin_achievements: yes
          plugin_achievements_threshold: C

          plugin_isocalendar: yes

          plugin_stars: yes

          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_lines: yes

          plugin_topics: yes
          plugin_topics_limit: 20

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
